# this file overrides the standard pstn data provided by the torasup gem
---
kh:
  operators:
    smart:
      default_mobile_subscriber_number_min: 203000
      metadata:
        short_code: "2442"
        smpp_server_id: "smart"
        caller_id: "2442"
        voip_gateway_host: "27.109.112.80"
        dial_string: "sofia/external/%{number_to_dial}@%{voip_gateway_host}"
        services:
          ifriendship_sms:
            type: "sms"
            name: "iFriendship SMS"
            short_code: "2442"
            unit_cost: "0.05"
            revenue_share: "0.3"
          ifriendship_ivr:
            type: "ivr"
            name: "iFriendship IVR"
            short_code: "2442"
            unit_cost: "0.1"
            revenue_share: "0.35"
    qb:
      metadata:
        short_code: "2442"
        caller_id: "2442"
        voip_gateway_host: "117.55.252.146"
        dial_string: "sofia/external/%{dial_string_number_prefix}%{number_to_dial}@%{voip_gateway_host}"
        dial_string_number_prefix: "2442"
        chargeable: false
        services:
          qb_friends:
            type: "charge"
            name: "qb Friends"
            short_code: "2442"
            unit_cost: "0.07"
            revenue_share: "0.4"
    cootel:
      metadata:
        short_code: "2442"
        smpp_server_id: "cootel"
        caller_id: "2442"
        voip_gateway_host: "103.5.126.165"
        dial_string: "sofia/external/%{dial_string_number_prefix}%{number_to_dial}@%{voip_gateway_host}:5061"
        dial_string_number_prefix: "00"
        services:
          cool_chat_sms:
            type: "sms"
            name: "Cool Chat SMS"
            short_code: "2442"
            unit_cost: "0.01"
            revenue_share: "0.4"
          cool_chat_ivr:
            type: "ivr"
            name: "Cool Chat IVR"
            short_code: "2442"
            unit_cost: "0.01"
            revenue_share: "0.4"
        blacklist:
        - "855382038039"
