# this file overrides the standard pstn data provided by the torasup gem
---
kh:
  operators:
    smart:
      metadata:
        short_code: "2442"
        nuntium_channel: "smart"
        mt_message_queue: "smart_mt_message_queue"
        caller_id: "2442"
        dial_string: "sofia/internal/%{number_to_dial}@27.109.112.80"
    beeline:
      metadata:
        short_code: "2442"
        nuntium_channel: "beeline"
        mt_message_queue: "beeline_mt_message_queue"
    hello:
      metadata:
        name: Hello
        short_code: "2442"
        nuntium_channel: "hello"
        mt_message_queue: "hello_mt_message_queue"
        caller_id: "2442"
        dial_string: "sofia/internal/%{number_to_dial}@27.109.112.80"
      prefixes:
      - '15'
      - '16'
      - '81'
      - '87'
      area_code_prefixes:
      - '45'
