# this file overrides the standard pstn data provided by the torasup gem
---
kh:
  operators:
    smart:
      metadata:
        caller_id: "2442"
        nuntium_channel: "smart"
        dial_string: "sofia/internal/%{number_to_dial}@27.109.112.12"
    beeline:
      metadata:
        nuntium_channel: "beeline"
    hello:
      metadata:
        name: Hello
        nuntium_channel: "hello"
        dial_string: "sofia/internal/%{number_to_dial}@27.109.112.12"
      prefixes:
      - '15'
      - '16'
      - '81'
      - '87'
      area_code_prefixes:
      - '45'
