development: &development
  database: chibi_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['CHIBI_DB_USERNAME'] %>
  password: <%= ENV['CHIBI_DB_PASSWORD'] %>

test:
  <<: *development
  database: chibi_test

# This gets overriden by Heroku
production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
