development: &development
  database: chibi_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: chibi

test:
  <<: *development
  database: chibi_test<%= ENV['TEST_ENV_NUMBER'] %>
