development: &development
  database: chibi_development
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: <%= ENV['CHIBI_DB_USERNAME'] %>
  password: <%= ENV['CHIBI_DB_PASSWORD'] %>

test:
  <<: *development
  database: chibi_test<%= ENV['TEST_ENV_NUMBER'] %>

# This gets overriden by Heroku
production:
  <<: *development
