# Sample localization file for English. Add more files in this directory for other locales.
# See https://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

en:
  i_am:
    - "(?:i am|i'm|im)"
  name:
    - "(?:(?:my )?names?(?:'s)?(?:\\s*(?:is|me))?(?:\\s*\\()?|i am|i'm|im)\\s*(?!\\bat\\b|\\bwhere\\b|\\bin\\b|\\ba\\b|\\bfine\\b|\\bok\\b|\\bsimple\\b|\\bworship\\b|\\bnot\\b|\\bey\\b|\\bi\\b|\\bold\\b|\\blive\\b|\\boh\\b|\\bis\\b|\\bme\\b|\\byear\\b|\\d+|\\b\\w+ing\\b)(\\b\\w+\\b)"
  years_old:
    - "(?:years?(?: old)?|yo|y)"
  girlfriend:
    - '(?:meet|find|chat|have|talk|need|looking for).+(?:gir?l|woman)'
    - 'gir?l\s?friend'
    - "gf"
    - "friend gir?l"
  girl:
    - f
  could_mean_girl_or_girlfriend:
    - "gir?l"
    - woman
    - "fem(?:a|e)le"
  boyfriend:
    - '(?:meet|find|chat|have|talk|need|looking for).+(?:boy|guy|man)'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - male
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - man
  friend:
    - '(?:(?:meet|find|chat|have|talk|need|looking for).+)?friends?'
kh:
  name:
    - '(?:chh?mu?ou?s)\s*(\b\w+\b)'
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rok).+)?m(?:i|e)t srey'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rok).+)?m(?:i|e)t (?:p|b)ros'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rok).+)?m(?:i|e)t'
