en:
  i_am:
    - "(?:(?:i\\s*)?am|i'm|im)(?:\\s*(?:a))?"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|me))?(?:\\s*(?:\\(|\\:))?|i am|i'm|im)\\s*(?!\\bat\\b|\\bwhere\\b|\\bin\\b|\\ba\\b|\\bfine\\b|\\bstay\\b|\\bok\\b|\\bsimple\\b|\\bworship\\b|\\bnot\\b|\\bey\\b|\\bi\\b|\\bold\\b|\\blive\\b|\\boh\\b|\\bgood\\b|\\bis\\b|\\band\\b|\\bme\\b|\\byear\\b|\\d+|\\b\\w+ing\\b)(\\b\\w+\\b)"
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*(?:gir?l|woman)'
    - 'gir?l\s?friend'
    - "gf"
    - "friend gir?l"
  girl:
    - f
  could_mean_girl_or_girlfriend:
    - "gir?l"
    - woman
    - "fem(?:a|e)le"
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*(?:boy|guy|man)'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - "m(?:a|e)le"
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - man
  friend:
    - '(?:(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*)?friends?'
kh:
  name:
    - '(?:chh?mu?ou?(?:r|s))\s*(\b\w+\b)'
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rok).+)?m(?:i|e)t srey'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rok).+)?m(?:i|e)t (?:p|b)ros'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rok).+)?m(?:i|e)t'
