en:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for |searching | searchimg )))(?:(?:i\\s*)?(?:\\b(?:am|i'm|iam|\\bim|me|\\bm\\b))(?:\\s*(?:a))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|iam|\\bim|\\bm\\b)\\s*"
  banned_names:
    - "available"
    - "currently"
    - "hungry"
    - "thirsty"
    - "help"
    - "crazy"
    - "horne?y"
    - "employe(?:e|r)"
    - "e?at"
    - "on"
    - "say"
    - "from"
    - "l?ate"
    - "in"
    - "fin?(?:(?:n|m)(?:d|e)d?)?"
    - "stay"
    - "agree"
    - "make"
    - "exactly"
    - "ok(?:(?:a|e)y)?"
    - "unlucky?"
    - "simple"
    - "worship"
    - "wife"
    - "poor"
    - "wonder(?:ful)?"
    - "not?(?:yet)?"
    - "(?:old|young)(?:er)?(?:ish)?(?:th(?:a|e)n)?"
    - "live?d?"
    - "oh"
    - "good"
    - "party"
    - "free"
    - "t?his"
    - "is"
    - "my"
    - "and?"
    - "me"
    - "plz"
    - "pleased?"
    - "sorr?y"
    - "year"
    - "single"
    - "too?"
    - "face(?:book)?"
    - "fb"
    - "verr?y"
    - "new"
    - "just"
    - "(?:well?)?come?"
    - "so"
    - "wa(?:i|n)t"
    - "sms"
    - "play(?:er)?"
    - "grade"
    - "great"
    - "watch"
    - "look"
    - "age"
    - "stt?u?d(?:y|ent?|ied)"
    - "work(?:er)?"
    - "like"
    - "teacher"
    - "stop"
    - "(?:tele)?phone?"
    - "mr"
    - "write"
    - "fun(?:ny)?"
    - "the"
    - "can"
    - "sleep"
    - "bored"
    - "afraid"
    - "sad"
    - "missed"
    - "name"
    - "g(?:l|r)a(?:d|t)e?"
    - "or"
    - "let"
    - "angry"
    - "k?now"
    - "fight"
    - "what"
    - "who"
    - "w?here"
    - "why"
    - "how"
    - "wish"
    - "with"
    - "hi"
    - "hello"
    - "thanks?"
    - "full?"
    - "was"
    - "home(?:town)?"
    - "still?"
    - "same"
    - "over"
    - "also"
    - "reall?y"
    - "(?:i|o)ff?"
    - "by"
    - "alone"
    - "lonely"
    - "only"
    - "birthday"
    - "happ?y"
    - "yes"
    - "top"
    - "need"
    - "s?he"
    - "sex"
    - "sit"
    - "take"
    - "(?:un)?well?"
    - "about"
    - "sure"
    - "easy"
    - "c?all"
    - "(?:al)?right"
    - "wrong"
    - "sick"
    - "ride"
    - "drive"
    - "dr(?:i|u)nk"
    - "farmm?er"
    - "forg(?:e|o)t"
    - "have"
    - "rea?pla?y"
    - "do"
    - "for"
    - "normal"
    - "listent?"
    - "sometimes?"
    - "ago"
    - "you"
    - "fri(?:e?nd)?"
    - "surpri(?:s|z)e"
    - "(?:w|v)ill"
    - "request"
    - "relax"
    - "answer"
    - "khmer"
    - "but"
    - "nice"
    - "each"
    - "difficult"
    - "pretty"
    - "prepare"
    - "add"
    - "tell"
    - "congratulation"
    - "fantastich?"
    - "business"
    - "read"
    - "hmm"
    - "pl"
    - "twenty"
    - "married"
    - "feel"
    - "chat"
    - "gay"
    - "go"
    - "finish"
    - "back"
    - "wom(?:a|e)n"
    - "sen(?:d|t)"
    - "namber"
    - "num(?:ber)?"
    - "(?:yo)?ur"
    - "(?:all?)?ready"
    - "bu(?:s|z)y"
    - '\d+(?:cm|kg)'
    - '(?:\w*)teen'
    - '\w+ing'
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girl:
    - "(?<!')f"
    - "g(?:i|r)(?:i|r)?ll?"
    - "wom(?:a|e)n"
    - "f(?:a|e)m(?:a|e)?le"
  boy:
    - "m(?:a|e)le"
    - "boy"
    - "guy"
    - "man"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:boy|guy|man) )(?:gir?l|wom(?:a|e)n)(?!\s*boy|guy|man))'
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:girl |gil |wom(?:a|e)n ))(?:boy|guy|man)(?!\s*gir?l|wom(?:a|e)n))'
  gay_boy:
    - "boy loves? boy"
    - "man loves? man"
  gay_girl:
    - "girl loves? girl"
kh:
  i_am:
    - "(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)"
  name:
    - "(?:(?:(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)\\s*(?:(?!chos)chh?o?m?u?o?u?r?s?(?:r|s)))|(?:(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)|(?:(?!chos)chh?o?m?u?o?u?r?s?(?:r|s))))(?:\\s*name\\s*)?(?:\\s*(?:\\(|\\:))?\\s*"
  banned_names:
    - "(?:ch|j)ou?r?ng"
    - "sour?sd(?:a|e)y"
    - "(?:n|d|t)ov"
    - "(?:ah?)?y(?:o|u)k?"
    - "e(?:i|y)"
    - "leng"
    - "v(?:e|i)ng"
    - "cf"
    - "loy"
    - "jeng"
    - "p(?:o?n)?g"
    - "baa?n"
    - "t(?:a|e)"
    - "m(?:a|e|i)(?:a|r)?n"
    - "rik(?:reay)?"
    - "some?"
    - "or?tt?"
    - "ko(?:r|m)"
    - "s(?:o|u)u?ks(?:a|u)bb?(?:a|e)?(?:i|y)(?:te)?"
    - "mor?(?:k|ng)"
    - "keang"
    - "aa?r?c?(?:j|h)"
    - "av(?:e|a)y"
    - "phe(?:t|d)"
    - "chh?mu?o?u?(?:r|s)"
    - "chear?"
    - "jia"
    - "skou?l"
    - "ti(?:c|k)"
    - "t(?:v|w)er"
    - "dou?ch"
    - "ngoy"
    - "ou?y"
    - "nah?"
    - "brab"
    - "nis"
    - "nham"
    - "nake"
    - "rekreay"
    - "or?(?:b|p)(?:sok)?"
    - "soks?"
    - "orkun"
    - "aos"
    - "t(?:a|o)mada"
    - "or?s"
    - "hery"
    - "k?m(?:i|e)an"
    - "(?:j|ch)bas"
    - "(?:k?n(?:h|y)(?:o|u)m)"
    - "ch(?:leu|oul)y"
    - "(?:ch|j)(?:a|o)m"
    - "k(?:a|o)m?ph?ong"
    - "bee?line"
    - "smart"
  years_old:
    - "(?:chnaa?m)"
  girl_gender_clues:
    - '(?:ch|j)as?'
  girl:
    - "srey"
  boy_gender_clues:
    - 'bar?t'
  boy:
    - '(?:b|p)ros'
  girlfriend:
    - '(?:(?:rou?k|m(?:i|e)r?t).+).*(?:(?<!(?:boy |(?:p|b)ros ))(?:srey|gir?l|\bf\b)(?!\s*boy|(?:p|b)ros))'
  boyfriend:
    - '(?:(?:rou?k|m(?:i|e)r?t).+).*(?:(?<!srey |girl |gil )(?:boy|(?:p|b)ros)(?!\s*srey|gir?l|\bf\b))'
ph:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for |searching |searchimg |nangita |nngta |naghahanap |nghhanp |kailangan |kausap |kachat |gusto |luking 4 |lukng 4 |looking 4 |luking for |seeking |serchng |searchng |serching )))(?:(?:\\bi\\s*)?(?:\\b(?:am|i'm|iam|\\bim|me|\\bm\\b|ako|aq| ako ay))(?:\\s*(?:(a\\b|ay|i)))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|iam|\\bim|\\bm\\b|ako ay si|ako c|ako i c|ako si|aq si|aq c|nako kay)\\s*|(?:(?:(?:my|aq|ako|ang|akong|aqng|ako ay)\\s+)?(?:name|nem|nym|pangalan|pngln|ngalan|ngln|ngan)\\s+(?:is|kay|ky|ko ay|q i|nako kay|nq ky|nko ky))\\s*"
  banned_names:
    - '(?:g)?wa(?:f|p)(?:a|o)'
    - '(?:wai|walang)\slo(?:a)?d'
    - 'adlaw'
    - 'adto'
    - 'agri'
    - 'akin(?:g)?'
    - 'akma'
    - 'ako(?:ng)?'
    - 'alam'
    - 'amig(?:a|o)'
    - 'ampo'
    - 'ampuan(?:an)?'
    - 'an(?:y)?os'
    - 'ana'
    - 'andam'
    - 'ang(?:ay|ga|kas)?'
    - 'anuman'
    - 'apan'
    - 'araw'
    - 'asa'
    - 'asawa'
    - 'at'
    - 'ate'
    - 'aunte'
    - 'awa'
    - 'awahi'
    - 'away'
    - 'ay'
    - 'ayo'
    - 'ba(?:ding|jot|yot|kla)'
    - 'ba(?:h|l)ay'
    - 'ba(?:j|h)e'
    - 'babae'
    - 'bag(?:\-)?o'
    - 'bahin'
    - 'baitang'
    - 'bakante'
    - 'bakit'
    - 'balik'
    - 'baliw'
    - 'basa(?:ha|hin)?'
    - 'bata'
    - 'bati'
    - 'bawat isa'
    - 'baynte'
    - 'before'
    - 'bitaw'
    - 'bitch'
    - 'boang'
    - 'boxing'
    - 'bryt'
    - 'buhat(?: sa unod)?'
    - 'buhay'
    - 'buhi'
    - 'bumalik'
    - 'busog'
    - 'byante'
    - 'c(?:j|y)a'
    - 'canton'
    - 'cel(?:l)?p(?:h)?on(?:e)?'
    - 'chixboy'
    - 'd'
    - 'da'
    - 'dad-a'
    - 'dagdag'
    - 'daghan gibuhat'
    - 'dah'
    - 'dalaga'
    - 'dali'
    - 'dalwampu'
    - 'dapat'
    - 'dati'
    - 'deliber'
    - 'dera'
    - 'di kaaya-aya'
    - 'dili'
    - 'dis'
    - 'disco'
    - 'diskarte'
    - 'dito'
    - 'dlga'
    - 'ds'
    - 'dugang'
    - 'dugay(?:an)?'
    - 'duh'
    - 'edad'
    - 'empleyado'
    - 'estudyante'
    - 'filipina'
    - 'fon(?:e)?'
    - 'fuck'
    - 'galing'
    - 'galit'
    - 'ganahan'
    - 'ganda(?:ng)?'
    - 'gawa(?:in)?'
    - 'gawas'
    - 'gikan'
    - 'ginoo'
    - 'gipadala'
    - 'giuhaw'
    - 'giunsa'
    - 'grado'
    - 'gulat'
    - 'guro'
    - 'gusto'
    - 'gutom'
    - 'hadlok'
    - 'hali'
    - 'hanap'
    - 'handa'
    - 'handsome'
    - 'hangyo'
    - 'hapit'
    - 'hayaan'
    - 'henyo'
    - 'higda'
    - 'hikam'
    - 'himo'
    - 'hinahon'
    - 'hindi pa'
    - 'hintay'
    - 'hmnn'
    - 'hmpf'
    - 'hubog'
    - 'human'
    - 'huminahon'
    - 'hunahuna'
    - 'hungit'
    - 'husto'
    - 'huwat'
    - 'ibaba(?:o|w)?'
    - 'iglip'
    - 'ikaw'
    - 'ilal(?:i|o)m'
    - 'ilawum'
    - 'imo(?:ng)?'
    - 'impaki'
    - 'ingon'
    - 'inip'
    - 'inis'
    - 'inom'
    - 'inusara'
    - 'ipadala'
    - 'isa(?: ra)?'
    - 'istorya(?:he)?'
    - 'isulti'
    - 'ito'
    - 'iyot'
    - 'jerjer'
    - 'ka'
    - 'kaalama(?:n)?'
    - 'kaarawan'
    - 'kaaya-aya'
    - 'kaayo'
    - 'kabit'
    - 'kadaw'
    - 'kahibaw'
    - 'kahibulungan'
    - 'kaibigan'
    - 'kailangan'
    - 'kain'
    - 'kalimot'
    - 'kalma'
    - 'kamangha-mangha'
    - 'kamao'
    - 'kanan'
    - 'kaniadto'
    - 'kantot'
    - 'kanya'
    - 'kaon'
    - 'kapa'
    - 'karaniwan'
    - 'kasagaran'
    - 'kasal'
    - 'kasalukuyan'
    - 'kasama'
    - 'katawanan'
    - 'katingalahan'
    - 'kauban'
    - 'kaw'
    - 'kay'
    - 'kaya'
    - 'kayat'
    - 'kibaw'
    - 'kiit'
    - 'kinahanglan'
    - 'kini'
    - 'kinig'
    - 'kinsa(?:y)?'
    - 'kumbati'
    - 'kumbira'
    - 'kumot'
    - 'kunin'
    - 'kurat'
    - 'kutoy'
    - 'kuya'
    - 'ky'
    - 'laay'
    - 'labas'
    - 'lakaw'
    - 'laklak'
    - 'lalis'
    - 'lamat'
    - 'lamay'
    - 'lang'
    - 'lantaw'
    - 'lasing'
    - 'lesbian'
    - 'libre'
    - 'libro'
    - 'limot'
    - 'lingaw-lingaw'
    - 'lingi(?:-a)?'
    - 'lingk(?:o|u)d'
    - 'lipat'
    - 'lipay'
    - 'lisud'
    - 'liwat'
    - 'lol(?:a|o)'
    - 'looy'
    - 'low(?:\s)?bat(?:t)?(?:ery)?'
    - 'lugar'
    - 'lungkot'
    - 'lungsod'
    - 'luya'
    - 'ma(?:na)?ng'
    - 'maayo(?:s)?'
    - 'mabuh(?:ay|i)'
    - 'madali'
    - 'madiskarte'
    - 'maestr(?:a|o)'
    - 'mag'
    - 'mag-aaral'
    - 'magaling'
    - 'maganda'
    - 'magbasa'
    - 'magduduwa'
    - 'magsasaka'
    - 'magu(?:-)?uma'
    - 'mahirap'
    - 'mahusay'
    - 'makinig'
    - 'malaki'
    - 'malas'
    - 'mali'
    - 'malipayon'
    - 'malungkot'
    - 'mana'
    - 'manganda'
    - 'manggawa'
    - 'mangha'
    - 'manghod'
    - 'maniho'
    - 'manlalaro'
    - 'manong'
    - 'manyak(?:is)?'
    - 'mao(?: ra)?'
    - 'maot'
    - 'maru'
    - 'masak(?:it|tan)'
    - 'masaya(?:hin)?'
    - 'matagal'
    - 'matalino'
    - 'matanda'
    - 'matsalam'
    - 'may ginagawa'
    - 'meron'
    - 'minaw'
    - 'mingaw'
    - 'minsan'
    - 'minyo'
    - 'mister'
    - 'mobil(?:e|phone)?'
    - 'morag'
    - 'mug-ot'
    - 'muntik'
    - 'na(?: pud)?'
    - 'naa(?: na)?'
    - 'nag-iisa'
    - 'nag-inusara'
    - 'nagparaos'
    - 'nakakatuwa'
    - 'nalibang'
    - 'nalipay'
    - 'nangita'
    - 'napaka'
    - 'napod'
    - 'nasakit'
    - 'nasiyahan'
    - 'natawhan'
    - 'natuwa'
    - 'naunsa'
    - 'nauuhaw'
    - 'nawong'
    - 'negosyo'
    - 'ngalan'
    - 'ngano(?: man)?'
    - 'ngayon'
    - 'nginig'
    - 'ngita'
    - 'ngl(?:a)?n'
    - 'nickname'
    - 'nimo'
    - 'nindot'
    - 'no.'
    - 'number'
    - 'numero'
    - 'o'
    - 'oi'
    - 'ok lang'
    - 'ok ra'
    - 'ok(?:a|o)y'
    - 'oks'
    - 'oo'
    - 'opo'
    - 'out'
    - 'p(?:i)?n(?:a|o)y'
    - 'p(?:o|u)d'
    - 'paano'
    - 'pabilin'
    - 'pabor'
    - 'padala'
    - 'pagbati'
    - 'pahalipay'
    - 'palautog'
    - 'palayaw'
    - 'paminaw'
    - 'panalangin'
    - 'pangalan'
    - 'pangit'
    - 'para'
    - 'parausan'
    - 'parih(?:a|o)'
    - 'pasagd(?:an|i)'
    - 'pasakya'
    - 'pasaylo'
    - 'patawad'
    - 'pawong'
    - 'pero'
    - 'pl(?:s|z)'
    - 'please'
    - 'pobre'
    - 'pulubi'
    - 'pun-(?:an|i)'
    - 'puno'
    - 'puta'
    - 'puyo'
    - 'relo'
    - 'sa'
    - 'saan'
    - 'sabi(?:hin)?'
    - 'sabot'
    - 'sagot'
    - 'saka'
    - 'sakay'
    - 'sakin'
    - 'sakit(?:an)?'
    - 'sakto(?: na)?'
    - 'salamat'
    - 'samba'
    - 'sambahin'
    - 'sapat'
    - 'sapayan'
    - 'sauna'
    - 'sayon'
    - 'sayop'
    - 'sha'
    - 'shit'
    - 'si(?:j|y)a'
    - 'sige'
    - 'simp(?:ly|ol)'
    - 'sino'
    - 'siping'
    - 'sir'
    - 'siyudad'
    - 'slmt'
    - 'studyante'
    - 'subo'
    - 'suko'
    - 'sulat'
    - 'sulod'
    - 'sulti'
    - 'sumang-ayon'
    - 'sumbag'
    - 'suntok'
    - 'surprise'
    - 'suwat'
    - 'sya'
    - 'taas'
    - 'tabang(?:i)?'
    - 'tabi'
    - 'tae'
    - 'taga'
    - 'tagsa'
    - 'takot'
    - 'talaw'
    - 'tama(?: na)?'
    - 'tanaw'
    - 'tandog'
    - 'tanggap'
    - 'tanggapin'
    - 'tapad'
    - 'tapos'
    - 'tawad'
    - 'tawag'
    - 'tawga'
    - 'techer'
    - 'telefon(?:e|o)'
    - 'tenk(?:s|yu|z)'
    - 'text'
    - 'tigduwa'
    - 'tingin'
    - 'tinood(?: ka)?'
    - 'tira'
    - 'tit(?:a|o)'
    - 'titser'
    - 'tog'
    - 'tomboy'
    - 'torjak'
    - 'totoo'
    - 'tr(?:a)?bahante'
    - 'trabaho'
    - 'tubag'
    - 'tulog'
    - 'tulong'
    - 'tulungan'
    - 'tumboy'
    - 'tungkol'
    - 'tuo'
    - 'tura'
    - 'txt'
    - 'u'
    - 'ug'
    - 'uhaw'
    - 'undang'
    - 'unsa(?: man)?'
    - 'unya'
    - 'upa'
    - 'upo'
    - 'usa'
    - 'usap'
    - 'uwagan'
    - 'uyon'
    - 'wala pa'
    - 'wat'
    - 'wise'
    - 'wui'
    - 'xa'
    - 'yan lang'
    - 'yayay'
  years_old:
    - "(?:y(?:ea)?rs?(?: old)?|yo|y\\-olds?|y\\b|an(?:y)?os|edad)"
  girl:
    - "(?<!')f"
    - "g(?:i|r|u)(?:i|r)?ll?"
    - "wom(?:a|e)n"
    - "f(?:a|e)m(?:a|e)?le"
    - "baba(?:y)?e"
    - "chi(?:x|ck|k)"
  boy:
    - "\\bm(?:a|e)le"
    - "boy"
    - "guy"
    - "\\bman"
    - "(?:la|l)?laki"
  girlfriend:
    - "(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g|nangita|nngta|naghahanap|nghhanp|kailangan|kausap|kachat|gusto|luking 4|lukng 4|looking 4|luking for|seeking|serchng|searchng|serching).*(?:(?<!(?:boy |guy |man |laki |lalaki ))(?:gir?l|wom(?:a|e)n|babaye|babae|chix|chick|chicks|cats)(?!\\s*boy|guy|man|laki|lalaki))"
  boyfriend:
    - "(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g|nangita|nngta|naghahanap|nghhanp|kailangan|kausap|kachat|gusto|luking 4|lukng 4|looking 4|luking for|seeking|serchng|searchng|serching).*(?:(?<!(?:girl |gil |wom(?:a|e)n |babaye |babae| chix| chick| chicks|cats ))(?:boy|guy|man|(?:la)?laki)(?!\\s*gir?l|wom(?:a|e)n|babaye|babae|chix|chick|chicks|cats))"
  gay_boy:
    - "(?:guy|boy|man|laki|lalaki)\\s+(?:loves?)\\s+(?:guy|boy|man|laki|lalaki)"
  gay_girl:
    - "(?:tomboy|tbird|lesbian|gir?l|wom(?:a|e)n|babaye|babae|chix|chick|chicks|cats)\\s+(?:loves?)\\s+(?:tomboy|tbird|lesbian|gir?l|wom(?:a|e)n|babaye|babae|chix|chick|chicks|cats)"
