en:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for )))(?:(?:i\\s*)?(?:am|i'm|im|me)(?:\\s*(?:a))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|im)\\s*(?!\\bat\\b|\\bwhere\\b|\\bin\\b|\\ba\\b|\\bfine\\b|\\bstay\\b|\\bok\\b|\\bsimple\\b|\\bworship\\b|\\bnot\\b|\\bey\\b|\\bi\\b|\\bold\\b|\\blive\\b|\\boh\\b|\\bgood\\b|\\bfree\\b|\\bis\\b|\\band\\b|\\bme\\b|\\bplz\\b|\\bplease\\b|\\bsorry\\b|\\byear\\b|\\bnew\\b|\\bwelcome\\b|\\d+|\\b\\w+ing\\b)(\\b\\w+\\b)"
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*(?:(?<!(?:boy|guy|man) )(?:gir?l|woman)(?!\s*boy|guy|man))'
    - 'gir?l\s?friend'
    - "gf"
    - "friend gir?l"
  girl:
    - f
  could_mean_girl_or_girlfriend:
    - "gir?l"
    - woman
    - "f(?:a|e)m(?:a|e)?le"
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*(?:(?<!(?:girl |gil |woman ))(?:boy|guy|man)(?!\s*gir?l|woman))'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - "m(?:a|e)le"
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - "man(?!\\?)"
  friend:
    - '(?:(?:meet|fin(?:d|e)|chat|have|talk|need|looking for).*)?(?<!(?:your |ur ))fri(?:ends?)?'
kh:
  i_am:
    - "(?:k?n(?:h|y)(?:o|u)m)"
  name:
    - "(?:(?:(?:k?n(?:h|y)(?:o|u)m)\\s*(?:chh?mu?ou?(?:r|s)))|(?:(?:k?n(?:h|y)(?:o|u)m)|(?:chh?mu?ou?(?:r|s))))(?:\\s*(?:\\(|\\:))?\\s*(?!\\bjong\\b|\\bsoursdey\\b|\\bnov\\b|\\ba\\b|\\bayu\\b|\\byu\\b)(\\b\\w+\\b)"
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!(?:boy |(?:p|b)ros ))(?:srey|gir?l|\bf\b)(?!\s*boy|(?:p|b)ros))'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!srey |girl |gil )(?:boy|(?:p|b)ros)(?!\s*srey|gir?l|\bf\b))'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rok).+)?m(?:i|e)t'
