en:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for |searching | searchimg )))(?:(?:i\\s*)?(?:\\b(?:am|i'm|im|me|\\bm\\b))(?:\\s*(?:a))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|im|\\bm\\b)\\s*"
  banned_names:
    - "e?at"
    - "from"
    - "l?ate"
    - "in"
    - "fin(?:d|e)d?"
    - "stay"
    - "ok"
    - "unlucky?"
    - "simple"
    - "worship"
    - "wonder(?:ful)?"
    - "not?"
    - "(?:old|young)(?:er)?"
    - "live"
    - "oh"
    - "good"
    - "free"
    - "is"
    - "my"
    - "and"
    - "me"
    - "plz"
    - "pleased?"
    - "sorr?y"
    - "year"
    - "single"
    - "too?"
    - "facebook"
    - "fb"
    - "verr?y"
    - "new"
    - "just"
    - "(?:wel)?come"
    - "so"
    - "wa(?:i|n)t"
    - "sms"
    - "play"
    - "grade"
    - "great"
    - "watch"
    - "age"
    - "stud(?:y|ent|ied)"
    - "work(?:er)?"
    - "like"
    - "teacher"
    - "stop"
    - "phone"
    - "mr"
    - "write"
    - "fun(?:ny)?"
    - "the"
    - "can"
    - "sleep"
    - "bored"
    - "missed"
    - "name"
    - "glade?"
    - "or"
    - "know"
    - "fight"
    - "what"
    - "who"
    - "where"
    - "why"
    - "how"
    - "wish"
    - "hi"
    - "hello"
    - "full?"
    - "was"
    - "home(?:town)?"
    - "still?"
    - "same"
    - "over"
    - "also"
    - "reall?y"
    - "(?:i|o)ff?"
    - "by"
    - "only"
    - "happ?y"
    - "yes"
    - "top"
    - "need"
    - "s?he"
    - "sex"
    - "sit"
    - "take"
    - "well"
    - "about"
    - "sure"
    - "easy"
    - "surpri(?:s|z)e"
    - "(?:w|v)ill"
    - "request"
    - "num(?:ber)?"
    - "(?:yo)?ur"
    - "(?:al)?ready"
    - "bu(?:s|z)y"
    - '\d+(?:cm|kg)'
    - '\w+ing'
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:boy|guy|man) )(?:gir?l|woman)(?!\s*boy|guy|man))'
    - 'gir?l\s?friend'
    - "gf"
    - "friend gir?l"
  girl:
    - f
  could_mean_girl_or_girlfriend:
    - "g(?:i|r)(?:i|r)?ll?"
    - woman
    - "f(?:a|e)m(?:a|e)?le"
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:girl |gil |woman ))(?:boy|guy|man)(?!\s*gir?l|woman))'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - "m(?:a|e)le"
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - "man(?!\\?)"
  friend:
    - '(?:(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*)?(?<!(?:your |ur ))fri(?:ends?)?'
kh:
  i_am:
    - "(?:k?n(?:h|y)(?:o|u)m)"
  name:
    - "(?:(?:(?:k?n(?:h|y)(?:o|u)m)\\s*(?:chh?mu?o?u?(?:r|s)))|(?:(?:k?n(?:h|y)(?:o|u)m)|(?:chh?mu?o?u?(?:r|s))))(?:\\s*name\\s*)?(?:\\s*(?:\\(|\\:))?\\s*"
  banned_names:
    - "(?:ch|j)or?ng"
    - "sour?sd(?:a|e)y"
    - "(?:n|d|t)ov"
    - "(?:ah?)?y(?:o|u)k?"
    - "e(?:i|y)"
    - "leng"
    - "cf"
    - "baa?n"
    - "t(?:a|e)"
    - "m(?:a|e|i)(?:a|r)?n"
    - "rik(?:reay)?"
    - "som"
    - "or?tt?"
    - "kor"
    - "s(?:o|u)ksabay(?:te)?"
    - "mor?(?:k|ng)"
    - "keang"
    - "aa?c?(?:j|h)"
    - "av(?:e|a)y"
    - "phe(?:t|d)"
    - "chh?mu?o?u?(?:r|s)"
    - "chear"
    - "skol"
    - "ti(?:c|k)"
    - "t(?:v|w)er"
    - "douch"
    - "ngoy"
    - "nah?"
    - "brab"
    - "(?:j|ch)bas"
    - "(?:k?n(?:h|y)(?:o|u)m)"
    - "ch(?:leu|oul)y"
    - "beeline"
    - "smart"
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!(?:boy |(?:p|b)ros ))(?:srey|gir?l|\bf\b)(?!\s*boy|(?:p|b)ros))'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!srey |girl |gil )(?:boy|(?:p|b)ros)(?!\s*srey|gir?l|\bf\b))'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rok).+)?m(?:i|e)t'
