en:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for |searching | searchimg )))(?:(?:i\\s*)?(?:\\b(?:am|i'm|\\bim|me|\\bm\\b))(?:\\s*(?:a))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|\\bim|\\bm\\b)\\s*"
  banned_names:
    - "e?at"
    - "on"
    - "from"
    - "l?ate"
    - "in"
    - "fi(?:(?:n|m)(?:d|e)d?)?"
    - "stay"
    - "ok"
    - "unlucky?"
    - "simple"
    - "worship"
    - "wonder(?:ful)?"
    - "not?"
    - "(?:old|young)(?:er)?"
    - "live?"
    - "oh"
    - "good"
    - "free"
    - "is"
    - "my"
    - "and?"
    - "me"
    - "plz"
    - "pleased?"
    - "sorr?y"
    - "year"
    - "single"
    - "too?"
    - "facebook"
    - "fb"
    - "verr?y"
    - "new"
    - "just"
    - "(?:well?)?come?"
    - "so"
    - "wa(?:i|n)t"
    - "sms"
    - "play(?:er)?"
    - "grade"
    - "great"
    - "watch"
    - "age"
    - "stud(?:y|ent|ied)"
    - "work(?:er)?"
    - "like"
    - "teacher"
    - "stop"
    - "phone"
    - "mr"
    - "write"
    - "fun(?:ny)?"
    - "the"
    - "can"
    - "sleep"
    - "bored"
    - "afraid"
    - "sad"
    - "missed"
    - "name"
    - "g(?:l|r)a(?:d|t)e?"
    - "or"
    - "let"
    - "angry"
    - "k?now"
    - "fight"
    - "what"
    - "who"
    - "w?here"
    - "why"
    - "how"
    - "wish"
    - "with"
    - "hi"
    - "hello"
    - "thanks?"
    - "full?"
    - "was"
    - "home(?:town)?"
    - "still?"
    - "same"
    - "over"
    - "also"
    - "reall?y"
    - "(?:i|o)ff?"
    - "by"
    - "alone"
    - "only"
    - "happ?y"
    - "yes"
    - "top"
    - "need"
    - "s?he"
    - "sex"
    - "sit"
    - "take"
    - "well"
    - "about"
    - "sure"
    - "easy"
    - "c?all"
    - "(?:al)?right"
    - "wrong"
    - "sick"
    - "ride"
    - "drive"
    - "farmm?er"
    - "forg(?:e|o)t"
    - "have"
    - "reply"
    - "do"
    - "normal"
    - "listent?"
    - "sometimes?"
    - "ago"
    - "you"
    - "fri(?:e?nd)?"
    - "surpri(?:s|z)e"
    - "(?:w|v)ill"
    - "request"
    - "relax"
    - "answer"
    - "khmer"
    - "but"
    - "nice"
    - "each"
    - "difficult"
    - "pretty"
    - "add"
    - "tell"
    - "congratulation"
    - "fantastich?"
    - "business"
    - "read"
    - "hmm"
    - "pl"
    - "twenty"
    - "married"
    - "feel"
    - "chat"
    - "gay"
    - "go"
    - "finish"
    - "back"
    - "wom(?:a|e)n"
    - "sen(?:d|t)"
    - "num(?:ber)?"
    - "(?:yo)?ur"
    - "(?:al)?ready"
    - "bu(?:s|z)y"
    - '\d+(?:cm|kg)'
    - '(?:\w*)teen'
    - '\w+ing'
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|fri(?:e?nd)?s?|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:boy|guy|man) )(?:gir?l|wom(?:a|e)n)(?!\s*boy|guy|man))'
    - 'gir?l\s?fri(?:e?nd)?s?'
    - "gf"
  girl:
    - "(?<!')f"
  could_mean_girl_or_girlfriend:
    - "g(?:i|r)(?:i|r)?ll?"
    - "wom(?:a|e)n"
    - "f(?:a|e)m(?:a|e)?le"
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|fri(?:e?nd)?s?|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:girl |gil |wom(?:a|e)n ))(?:boy|guy|man)(?!\s*gir?l|wom(?:a|e)n))'
    - 'boy\s?fri(?:e?nd)?s?'
    - bf
  boy:
    - "m(?:a|e)le"
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - "man(?!\\?)"
  friend:
    - '(?:(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*)?(?<!(?:your |ur ))fri(?:e?nds?)?'
kh:
  i_am:
    - "(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)"
  name:
    - "(?:(?:(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)\\s*(?:chh?o?m?u?o?u?r?s?(?:r|s)))|(?:(?:k?(?<!p|h)n(?:h|y)?(?:o|u)m)|(?:chh?o?m?u?o?u?r?s?(?:r|s))))(?:\\s*name\\s*)?(?:\\s*(?:\\(|\\:))?\\s*"
  banned_names:
    - "(?:ch|j)or?ng"
    - "sour?sd(?:a|e)y"
    - "(?:n|d|t)ov"
    - "(?:ah?)?y(?:o|u)k?"
    - "e(?:i|y)"
    - "leng"
    - "cf"
    - "baa?n"
    - "t(?:a|e)"
    - "m(?:a|e|i)(?:a|r)?n"
    - "rik(?:reay)?"
    - "some?"
    - "or?tt?"
    - "ko(?:r|m)"
    - "s(?:o|u)u?ksabb?(?:a|e)y(?:te)?"
    - "mor?(?:k|ng)"
    - "keang"
    - "aa?r?c?(?:j|h)"
    - "av(?:e|a)y"
    - "phe(?:t|d)"
    - "chh?mu?o?u?(?:r|s)"
    - "chear?"
    - "jia"
    - "skou?l"
    - "ti(?:c|k)"
    - "t(?:v|w)er"
    - "douch"
    - "ngoy"
    - "ou?y"
    - "nah?"
    - "brab"
    - "rekreay"
    - "or?(?:b|p)(?:sok)?"
    - "soks?"
    - "orkun"
    - "aos"
    - "tomada"
    - "or?s"
    - "hery"
    - "k?m(?:i|e)an"
    - "(?:j|ch)bas"
    - "(?:k?n(?:h|y)(?:o|u)m)"
    - "ch(?:leu|oul)y"
    - "(?:ch|j)(?:a|o)m"
    - "k(?:a|o)mpong"
    - "bee?line"
    - "smart"
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rou?k|m(?:i|e)r?t).+).*(?:(?<!(?:boy |(?:p|b)ros ))(?:srey|gir?l|\bf\b)(?!\s*boy|(?:p|b)ros))'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rou?k|m(?:i|e)r?t).+).*(?:(?<!srey |girl |gil )(?:boy|(?:p|b)ros)(?!\s*srey|gir?l|\bf\b))'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rou?k).+)?m(?:i|e)r?t'
