# Sample localization file for English. Add more files in this directory for other locales.
# See https://github.com/svenfuchs/rails-i18n/tree/master/rails%2Flocale for starting points.

en:
  name:
    - "(?:my name is|i am|i'm|im)\\s*(?!\\bat\\b|\\bin\\b|\\ba\\b|\\b\\w+ing\\b)(\\b\\w+\\b)"
  years_old:
    - "(?:years?(?: old)?|yo)"
  girlfriend:
    - '(?:meet|find|chat|have|talk).+(?:girl|woman)'
    - 'girl\s?friend'
    - gf
    - friend girl
  girl:
    - f
    - female
  could_mean_girl_or_girlfriend:
    - girl
    - woman
  boyfriend:
    - '(?:meet|find|chat|have|talk).+(?:boy|guy|man)'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - "(?<!')m"
    - male
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - man
  friend:
    - 'friends?'
kh:
  name:
    - '(?:chh?mu?ou?s)\s*(\b\w+\b)'
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - 'm(?:i|e)t srey'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - 'm(?:i|e)t (?:p|b)ros'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - 'm(?:i|e)t'
