en:
  i_am:
    - "(?:(?<!(?:meet |fin(?:d|e) |chat |have |talk |need |looking for |searching | searchimg )))(?:(?:i\\s*)?(?:\\b(?:am|i'm|im|me|\\bm\\b))(?:\\s*(?:a))?)"
  name:
    - "(?:(?:my )?na(?:m|n)es?(?:'s)?(?:\\s*(?:is|m(?:e|y)))?(?:\\s*(?:\\(|\\:))?|i am|i'm|im|\\bm\\b)\\s*"
  banned_names:
    - "at"
    - "from"
    - "where"
    - "in"
    - "fin(?:d|e)"
    - "stay"
    - "ok"
    - "simple"
    - "worship"
    - "not"
    - "old"
    - "live"
    - "oh"
    - "good"
    - "free"
    - "is"
    - "and"
    - "me"
    - "plz"
    - "please"
    - "sorry"
    - "year"
    - "single"
    - "too?"
    - "facebook"
    - "fb"
    - "verr?y"
    - "very"
    - "new"
    - "just"
    - "welcome"
    - "so"
    - "want"
    - "sms"
    - "play"
    - "grade"
    - "watch"
    - "age"
    - "study"
    - "work"
    - "like"
    - "teacher"
    - "stop"
    - "phone"
    - "mr"
    - "bu(?:s|z)y"
    - '\d+(?:cm|kg)'
    - '\w+ing'
  years_old:
    - "(?:years?(?: old)?|yo|y\\-olds?|y)"
  girlfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:boy|guy|man) )(?:gir?l|woman)(?!\s*boy|guy|man))'
    - 'gir?l\s?friend'
    - "gf"
    - "friend gir?l"
  girl:
    - f
  could_mean_girl_or_girlfriend:
    - "g(?:i|r)(?:i|r)?l"
    - woman
    - "f(?:a|e)m(?:a|e)?le"
  boyfriend:
    - '(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*(?:(?<!(?:girl |gil |woman ))(?:boy|guy|man)(?!\s*gir?l|woman))'
    - 'boy\s?friend'
    - bf
    - friend boy
  boy:
    - "m(?:a|e)le"
  could_mean_boy_or_boyfriend:
    - boy
    - guy
    - "man(?!\\?)"
  friend:
    - '(?:(?:meet|fin(?:d|e)|chat|have|talk|need|looking for|searchi(?:n|m)g).*)?(?<!(?:your |ur ))fri(?:ends?)?'
kh:
  i_am:
    - "(?:k?n(?:h|y)(?:o|u)m)"
  name:
    - "(?:(?:(?:k?n(?:h|y)(?:o|u)m)\\s*(?:chh?mu?ou?(?:r|s)))|(?:(?:k?n(?:h|y)(?:o|u)m)|(?:chh?mu?ou?(?:r|s))))(?:\\s*name\\s*)?(?:\\s*(?:\\(|\\:))?\\s*"
  banned_names:
    - "jong"
    - "soursdey"
    - "(?:n|d|t)ov"
    - "a?yu"
    - "ey"
    - "leng"
    - "cf"
    - "baa?n"
    - "ta"
    - "m(?:a|e|i)n"
    - "rik"
    - "som"
  years_old:
    - "(?:chnaa?m)"
  girlfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!(?:boy |(?:p|b)ros ))(?:srey|gir?l|\bf\b)(?!\s*boy|(?:p|b)ros))'
  girl:
    - '(ch|j)as?'
  could_mean_girl_or_girlfriend:
    - srey
  boyfriend:
    - '(?:(?:rok|m(?:i|e)t).+).*(?:(?<!srey |girl |gil )(?:boy|(?:p|b)ros)(?!\s*srey|gir?l|\bf\b))'
  boy:
    - 'bar?t'
  could_mean_boy_or_boyfriend:
    - '(?:b|p)ros'
  friend:
    - '(?:(?:rok).+)?m(?:i|e)t'
