development:
  url: http://nuntium.instedd.org
  account: swpp
  application: sms_dating
  password: dating
  incoming_user: sms
  incoming_password: dating

production:
  url: http://nuntium.instedd.org
  account: swpp
  application: sms_dating
  password: dating
  incoming_user: sms
  incoming_password: dating

test:
  url: http://nuntium.instedd.org
  account: swpp
  application: sms_dating
  password: dating
  incoming_user: sms
  incoming_password: dating
