  # Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.

production: &production
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_fog_directory: <%= ENV["AWS_FOG_DIRECTORY"] %>
  broadcast_hours_min: <%= ENV["BROADCAST_HOURS_MIN"] %>
  broadcast_hours_max: <%= ENV["BROADCAST_HOURS_MAX"] %>
  broadcast_max_queued: <%= ENV["BROADCAST_MAX_QUEUED"] %>
  call_data_record_creator_queue: <%= ENV["CALL_DATA_RECORD_CREATOR_QUEUE"] %>
  charge_request_updater_queue:  <%= ENV["CHARGE_REQUEST_UPDATER_QUEUE"] %>
  charge_requester_external_queue: <%= ENV["CHARGE_REQUESTER_EXTERNAL_QUEUE"] %>
  charge_request_long_timeout_duration_hours: <%= ENV["CHARGE_REQUEST_LONG_TIMEOUT_DURATION_HOURS"] %>
  charge_request_short_timeout_duration_seconds: <%= ENV["CHARGE_REQUEST_SHORT_TIMEOUT_DURATION_SECONDS"] %>
  chat_cleanup_age_days: <%= ENV["CHAT_CLEANUP_AGE_DAYS"] %>
  chat_intended_for_limit: <%= ENV["CHAT_INTENDED_FOR_LIMIT"] %>
  chat_max_to_activate: <%= ENV["CHAT_MAX_TO_ACTIVATE"] %>
  chat_max_one_sided_interactions: <%= ENV["CHAT_MAX_ONE_SIDED_INTERACTIONS"] %>
  chat_permanent_timeout_minutes: <%= ENV["CHAT_PERMANENT_TIMEOUT_MINUTES"] %>
  chat_provisional_timeout_minutes: <%= ENV["CHAT_PROVISIONAL_TIMEOUT_MINUTES"] %>
  chat_expirer_queue: <%= ENV["CHAT_EXPIRER_QUEUE"] %>
  chat_reinvigorator_queue: <%= ENV["CHAT_REINVIGORATOR_QUEUE"] %>
  default_country_code: <%= ENV["DEFAULT_COUNTRY_CODE"] %>
  default_pbx_dial_string: <%= ENV["DEFAULT_PBX_DIAL_STRING"] %>
  failed_replies_cutoff: <%= ENV["FAILED_REPLIES_CUTOFF"] %>
  friend_messenger_queue: <%= ENV["FRIEND_MESSENGER_QUEUE"] %>
  http_basic_auth_admin_user: <%= ENV["HTTP_BASIC_AUTH_ADMIN_USER"] %>
  http_basic_auth_admin_password: <%= ENV["HTTP_BASIC_AUTH_ADMIN_PASSWORD"] %>
  http_basic_auth_phone_call_user: <%= ENV["HTTP_BASIC_AUTH_PHONE_CALL_USER"] %>
  http_basic_auth_phone_call_password: <%= ENV["HTTP_BASIC_AUTH_PHONE_CALL_PASSWORD"] %>
  http_basic_auth_message_user: <%= ENV["HTTP_BASIC_AUTH_MESSAGE_USER"] %>
  http_basic_auth_message_password: <%= ENV["HTTP_BASIC_AUTH_MESSAGE_PASSWORD"] %>
  http_basic_auth_call_data_record_user: <%= ENV["HTTP_BASIC_AUTH_CALL_DATA_RECORD_USER"] %>
  http_basic_auth_call_data_record_password: <%= ENV["HTTP_BASIC_AUTH_CALL_DATA_RECORD_PASSWORD"] %>
  internal_queues: <%= ENV["INTERNAL_QUEUES"] %>
  locator_queue: <%= ENV["LOCATOR_QUEUE"] %>
  max_simultaneous_dials: <%= ENV["MAX_SIMULTANEOUS_DIALS"] %>
  message_awaiting_parts_timeout: <%= ENV["MESSAGE_AWAITING_PARTS_TIMEOUT"] %>
  message_cleanup_queue: <%= ENV["MESSAGE_CLEANUP_QUEUE"] %>
  message_part_processor_queue: <%= ENV["MESSAGE_PART_PROCESSOR_QUEUE"] %>
  message_part_processor_delay: <%= ENV["MESSAGE_PART_PROCESSOR_DELAY"] %>
  message_processor_queue: <%= ENV["MESSAGE_PROCESSOR_QUEUE"] %>
  msisdn_discovery_queue: <%= ENV["MSISDN_DISCOVERY_QUEUE"] %>
  phone_call_processor_queue: <%= ENV["PHONE_CALL_PROCESSOR_QUEUE"] %>
  phone_call_completion_queue: <%= ENV["PHONE_CALL_COMPLETION_QUEUE"] %>
  recent_interaction_cutoff_months: <%= ENV["RECENT_INTERACTION_CUTOFF_MONTHS"] %>
  remind_inactivity_cutoff_days: <%= ENV["REMIND_INACTIVITY_CUTOFF_DAYS"] %>
  remind_max: <%= ENV["REMIND_MAX"] %>
  report_generator_queue: <%= ENV["REPORT_GENERATOR_QUEUE"] %>
  scheduled_queue:  <%= ENV["SCHEDULED_QUEUE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  smpp_delivery_receipt_update_status_queue: <%= ENV["SMPP_DELIVERY_RECEIPT_UPDATE_STATUS_QUEUE"] %>
  smpp_external_mt_message_queue: <%= ENV["SMPP_EXTERNAL_MT_MESSAGE_QUEUE"] %>
  smpp_internal_mt_message_queue: <%= ENV["SMPP_INTERNAL_MT_MESSAGE_QUEUE"] %>
  smpp_mo_message_received_queue: <%= ENV["SMPP_MO_MESSAGE_RECEIVED_QUEUE"] %>
  smpp_mt_message_update_status_queue: <%= ENV["SMPP_MT_MESSAGE_UPDATE_STATUS_QUEUE"] %>
  text_new_for_new_chat: <%= ENV["TEXT_NEW_FOR_NEW_CHAT"] %>
  twilio_application_sid: <%= ENV["TWILIO_APPLICATION_SID"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_cdr_fetcher_queue: <%= ENV["TWILIO_CDR_FETCHER_QUEUE"] %>
  twilio_message_status_fetcher_queue: <%= ENV["TWILIO_MESSAGE_STATUS_FETCHER_QUEUE"] %>
  twilio_message_status_fetcher_delay: <%= ENV["TWILIO_MESSAGE_STATUS_FETCHER_DELAY"] %>
  twilio_mt_message_received_queue: <%= ENV["TWILIO_MT_MESSAGE_RECEIVED_QUEUE"] %>
  twilio_mt_message_sender_queue: <%= ENV["TWILIO_MT_MESSAGE_SENDER_QUEUE"] %>
  twilio_outgoing_numbers: <%= ENV["TWILIO_OUTGOING_NUMBERS"] %>
  twilio_outgoing_numbers_sms_capable: <%= ENV["TWILIO_OUTGOING_NUMBERS_SMS_CAPABLE"] %>
  user_cleanup_queue: <%= ENV["USER_CLEANUP_QUEUE"] %>
  user_hours_min: <%= ENV["USER_HOURS_MIN"] %>
  user_hours_max: <%= ENV["USER_HOURS_MAX"] %>
  user_reminderer_queue: <%= ENV["USER_REMINDERER_QUEUE"] %>

development: &development
  <<: *production
  aws_access_key_id: "aws_access_key_id"
  aws_secret_access_key: "aws_secret_access_key"
  aws_fog_directory: "aws-fog-directory"
  broadcast_hours_min: 8
  broadcast_hours_max: 20
  broadcast_max_queued: 100
  call_data_record_creator_queue: "very_high"
  charge_request_long_timeout_duration_hours: 24
  charge_request_short_timeout_duration_seconds: 20
  charge_request_updater_queue: "critical"
  charge_requester_external_queue: "charge_requester_queue"
  chat_cleanup_age_days: 30
  chat_intended_for_limit: ""
  chat_max_to_activate: 5
  chat_max_one_sided_interactions: 3
  chat_permanent_timeout_minutes: 1440
  chat_provisional_timeout_minutes: 10
  chat_expirer_queue: "high"
  chat_reinvigorator_queue: "high"
  default_country_code: 855
  default_pbx_dial_string: "sofia/gateway/didlogic/%{number_to_dial}"
  failed_replies_cutoff: 3
  friend_messenger_queue: "default"
  text_new_for_new_chat: 1
  http_basic_auth_admin_user: "admin"
  http_basic_auth_admin_password: "secret"
  http_basic_auth_phone_call_user: "phonecall_user"
  http_basic_auth_phone_call_password: "secret"
  http_basic_auth_message_user: "message_user"
  http_basic_auth_message_password: "secret"
  http_basic_auth_call_data_record_user: "cdr_user"
  http_basic_auth_call_data_record_password: "secret"
  internal_queues: "scheduled:very_low:low:default:high:very_high:urgent:critical"
  locator_queue: "high"
  max_simultaneous_dials: 5
  message_cleanup_queue: "low"
  message_part_processor_queue: "urgent"
  message_part_processor_delay: 5
  message_processor_queue: "urgent"
  message_awaiting_parts_timeout: "300"
  msisdn_discovery_queue: "very_low"
  phone_call_processor_queue: "critical"
  phone_call_completion_queue: "default"
  recent_interaction_cutoff_months: 1
  remind_max: 100
  remind_inactivity_cutoff_days: 5
  report_generator_queue: "high"
  scheduled_queue: "scheduled"
  secret_key_base: 645976b42c3a32958a31369109a3ee3cfc5602b2749d70525a10e0444086670ec5a8ecc15b70176cc5e8bf084fc8893ca3c302c118f021708364db62827ce696
  smpp_external_mt_message_queue: "chibi_external_mt_message_queue"
  smpp_internal_mt_message_queue: "urgent"
  smpp_mt_message_update_status_queue: "high"
  smpp_delivery_receipt_update_status_queue: "high"
  smpp_mo_message_received_queue: "urgent"
  twilio_application_sid: "twilio_application_sid"
  twilio_account_sid: "twilio_account_sid"
  twilio_auth_token: "twilio_auth_token"
  twilio_cdr_fetcher_queue: "high"
  twilio_message_status_fetcher_queue: "high"
  twilio_message_status_fetcher_delay: 3600
  twilio_mt_message_received_queue: "high"
  twilio_mt_message_sender_queue: "urgent"
  twilio_outgoing_numbers: "855383838380:85513300324:14156926280"
  twilio_outgoing_numbers_sms_capable: 14156926280
  user_cleanup_queue: "low"
  user_hours_min: 8
  user_hours_max: 20
  user_reminderer_queue: "low"

test:
  <<: *development
  secret_key_base: f360ccb599342d4ed6b83cbb4397479433db980bb7e363199d443409eb6b94447a2b7ba19949e714f70541a0956e38ec4a745562dfed79b457a7ec70e429ad6b
